=== aweframework/awe/awe-framework/awe-generic-screens/src/main/resources/schemas/awe/actions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!--
  ==============================================================================
  Definition
  ==============================================================================
  -->

  <xs:annotation>
    <xs:appinfo>awe Actions Schema</xs:appinfo>
    <xs:documentation xml:lang="en">
      This Schema defines the way an awe Actions file must be structured
    </xs:documentation>
  </xs:annotation>

  <!--
  ==============================================================================
  Includes
  ==============================================================================
  -->

  <xs:include schemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/general.xsd"/>

  <!--
  ==============================================================================
  Elements
  ==============================================================================
  -->

  <!-- Actions Element -->
  <xs:element name="actions" type="actionsType">
    <xs:unique name="ActionNameUnique">
      <xs:selector xpath=".//target" />
      <xs:field xpath="@id" />
    </xs:unique>
  </xs:element>

  <!-- Action Element -->
  <xs:element name="action" type="actionType"/>

  <!-- Call Element -->
  <xs:element name="call" type="callType"/>

  <!-- Answer Element -->
  <xs:element name="answer" type="answerType"/>

  <!-- Response Element -->
  <xs:element name="response" type="responseType"/>

  <!-- Type Element -->
  <xs:element name="type" type="xs:string"/>

  <!-- Destination Element -->
  <xs:element name="destination" type="xs:string"/>

  <!-- Async Element -->
  <xs:element name="async" type="xs:string"/>

  <!-- Silent Element -->
  <xs:element name="silent" type="xs:string"/>

  <!-- Parameters Element -->
  <xs:element name="parameters" type="parametersType"/>

  <!-- Parameter Element -->
  <xs:element name="parameter" type="parameterType"/>

  <!--
  ==============================================================================
  Attribute Groups
  ==============================================================================
  -->

  <!-- Action Attributes -->
  <xs:attributeGroup name="actionAttr">
    <xs:attribute name="format" use="required" type="xs:string"/>
    <xs:attribute name="id" use="required" type="xs:string"/>
  </xs:attributeGroup>

  <!-- Parameter Attributes -->
  <xs:attributeGroup name="parameterAttr">
    <xs:attribute name="name" use="required" type="xs:string"/>
    <xs:attribute name="value"/>
    <xs:attribute name="variable" type="xs:string"/>
    <xs:attribute name="parameter" type="xs:string"/>
  </xs:attributeGroup>

  <!--
  ==============================================================================
  Group definitions
  ==============================================================================
  -->

  <!-- Actions Group -->
  <xs:group name="actionsGroup">
    <xs:choice>
      <xs:element ref="action"/>
    </xs:choice>
  </xs:group>

  <!-- Action Group -->
  <xs:group name="actionGroup">
    <xs:sequence>
      <xs:element ref="call"   minOccurs="1" maxOccurs="1"/>
      <xs:element ref="answer" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:group>

  <!-- Answer Group -->
  <xs:group name="answerGroup">
    <xs:sequence>
      <xs:element ref="response"/>
    </xs:sequence>
  </xs:group>

  <!--
  ==============================================================================
  Type definitions
  ==============================================================================
  -->

  <!-- Actions Type -->
  <xs:complexType name="actionsType">
    <xs:group ref="actionsGroup" minOccurs="0" maxOccurs="unbounded"/>
  </xs:complexType>

  <!-- Action Type -->
  <xs:complexType name="actionType">
    <xs:group ref="actionGroup"/>
    <xs:attributeGroup ref="actionAttr"/>
  </xs:complexType>

  <!-- Call Type -->
  <xs:complexType name="callType">
    <xs:attribute name="service" use="required" type="xs:string"/>
  </xs:complexType>

  <!-- Answer Type -->
  <xs:complexType name="answerType">
    <xs:group ref="answerGroup" minOccurs="1" maxOccurs="unbounded"/>
    <xs:attribute name="type" use="required" type="xs:string"/>
  </xs:complexType>

  <!-- Response Type -->
  <xs:complexType name="responseType">
    <xs:sequence>
      <xs:element ref="type"/>
      <xs:element minOccurs="0" ref="async"/>
      <xs:element minOccurs="0" ref="silent"/>
      <xs:element minOccurs="0" ref="destination"/>
      <xs:element minOccurs="0" ref="parameters"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Parameters Type -->
  <xs:complexType name="parametersType">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" ref="parameter"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Parameter Type -->
  <xs:complexType name="parameterType">
    <xs:attributeGroup ref="parameterAttr"/>
  </xs:complexType>

</xs:schema>

=== aweframework/awe/awe-framework/awe-generic-screens/src/main/resources/application/awe/global/Actions.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : Actions.xml
    Created on : 5 de febrero de 2010, 12:46
    Author     : Pablo GARCIA
    Description:
        Purpose of the document follows.
-->

<actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/actions.xsd">

  <!-- DEFAULT ERROR! DO NOT REMOVE -->
  <action id="DEFAULT_ERROR" format="JSON">
    <call service="NONE" />
    <answer type="error">
      <response>
        <type>end-load</type>
      </response>
      <response>
        <type>message</type>
        <parameters>
          <parameter name="type" variable="MESSAGE_TYPE" />
          <parameter name="title" variable="MESSAGE_TITLE" />
          <parameter name="message" variable="MESSAGE_DESCRIPTION" />
        </parameters>
      </response>
      <response>
        <type>cancel</type>
      </response>
    </answer>
  </action>

  <!-- LOGIN ACTION -->
  <action id="login" format="HTML">
    <call service="logout" />
  </action>

  <!-- AFTER LOGIN ACTION -->
  <action id="afterLogin" format="JSON">
    <call service="login"/>
    <answer type="ok">
      <response>
        <type>end-load</type>
      </response>
    </answer>
    <answer type="warning">
      <response>
        <type>end-load</type>
      </response>
      <response>
        <type>message</type>
        <parameters>
          <parameter name="type" variable="MESSAGE_TYPE" />
          <parameter name="title" variable="MESSAGE_TITLE" />
          <parameter name="message" variable="MESSAGE_DESCRIPTION" />
        </parameters>
      </response>
      <response>
        <type>cancel</type>
      </response>
    </answer>
    <answer type="error">
      <response>
        <type>end-load</type>
      </response>
      <response>
        <type>message</type>
        <parameters>
          <parameter name="type" variable="MESSAGE_TYPE" />
          <parameter name="title" variable="MESSAGE_TITLE" />
          <parameter name="message" variable="MESSAGE_DESCRIPTION" />
        </parameters>
      </response>
      <response>
        <type>cancel</type>
      </response>
    </answer>
  </action>

  <!-- LOGOUT ACTION -->
  <action id="logout" format="HTML">
    <call service="logout" />
  </action>


  <!-- LOGOUT ACTION -->
  <action id="logoutRedirect" format="JSON">
    <call service="logout" />
    <answer type="ok">
      <response>
        <type>end-load</type>
      </response>
    </answer>
    <answer type="error">
      <response>
        <type>end-load</type>
      </response>
      <response>
        <type>message</type>
        <parameters>
          <parameter name="type" variable="MESSAGE_TYPE" />
          <parameter name="title" variable="MESSAGE_TITLE" />
          <parameter name="message" variable="MESSAGE_DESCRIPTION" />
        </parameters>
      </response>
      <response>
        <type>cancel</type>
      </response>
    </answer>
  </action>

  <!-- REFRESH MENU ACTION -->
  <action id="refresh-menu" format="JSON">
    <call service="refreshMenu"/>
    <answer type="ok">
      <response>
        <type>change-menu</type>
        <parameters>
          <parameter name="options" variable="MENU_OPTIONS" />
        </parameters>
      </response>
      <response>
        <type>end-load</type>
      </response>
    </answer>
    <answer type="error">
      <response>
        <type>end-load</type>
      </response>
      <response>
        <type>message</type>
        <parameters>
          <parameter name="type"   variable="MESSAGE_TYPE" />
          <parameter name="title"   variable="MESSAGE_TITLE" />
          <parameter name="message" variable="MESSAGE_DESCRIPTION" />
        </parameters>
      </response>
      <response>
        <type>cancel</type>
      </response>
    </answer>
  </action>

  <!-- MAINTAIN ACTION -->
  <action id="maintain" format="JSON">
    <call service="launchMaintain" />
    <answer type="ok">
      <response>
        <type>end-load</type>
      </response>
      <response>
        <type>message</type>
        <parameters>
          <parameter name="type" variable="MESSAGE_TYPE" />
          <parameter name="title" variable="MESSAGE_TITLE" />
          <parameter name="message" variable="MESSAGE_DESCRIPTION" />
          <parameter name="result_details" variable="MESSAGE_RESULT_DETAILS" />
        </parameters>
      </response>
    </answer>
    <answer type="warning">
      <response>
        <type>end-load</type>
      </response>
      <response>
        <type>message</type>
        <parameters>
          <parameter name="type" variable="MESSAGE_TYPE" />
          <parameter name="title" variable="MESSAGE_TITLE" />
          <parameter name="message" variable="MESSAGE_DESCRIPTION" />
        </parameters>
      </response>
      <response>
        <type>cancel</type>
      </response>
    </answer>
    <answer type="info">
      <response>
        <type>end-load</type>
      </response>
      <response>
        <type>message</type>
        <parameters>
          <parameter name="type" variable="MESSAGE_TYPE" />
          <parameter name="title" variable="MESSAGE_TITLE" />
          <parameter name="message" variable="MESSAGE_DESCRIPTION" />
        </parameters>
      </response>
    </answer>
    <answer type="error">
      <response>
        <type>end-load</type>
      </response>
      <response>
        <type>message</type>
        <parameters>
          <parameter name="type" value="error" />
          <parameter name="title" variable="MESSAGE_TITLE" />
          <parameter name="message" variable="MESSAGE_DESCRIPTION" />
        </parameters>
      </response>
      <response>
        <type>cancel</type>
      </response>
    </answer>
  </action>

  <!-- MAINTAIN SILENT ACTION -->
  <action id="maintain-silent" format="JSON">
    <call service="launchMaintain" />
    <answer type="ok">
      <response>
        <type>end-load</type>
      </response>
    </answer>
    <answer type="warning">
      <response>
        <type>end-load</type>
      </response>
      <response>
        <type>message</type>
        <parameters>
          <parameter name="type" variable="MESSAGE_TYPE" />
          <parameter name="title" variable="MESSAGE_TITLE" />
          <parameter name="message" variable="MESSAGE_DESCRIPTION" />
        </parameters>
      </response>
      <response>
        <type>cancel</type>
      </response>
    </answer>
    <answer type="info">
      <response>
        <type>end-load</type>
      </response>
      <response>
        <type>message</type>
        <parameters>
          <parameter name="type" variable="MESSAGE_TYPE" />
          <parameter name="title" variable="MESSAGE_TITLE" />
          <parameter name="message" variable="MESSAGE_DESCRIPTION" />
        </parameters>
      </response>
    </answer>
    <answer type="error">
      <response>
        <type>end-load</type>
      </response>
      <response>
        <type>message</type>
        <parameters>
          <parameter name="type" value="error" />
          <parameter name="title" variable="MESSAGE_TITLE" />
          <parameter name="message" variable="MESSAGE_DESCRIPTION" />
        </parameters>
      </response>
      <response>
        <type>cancel</type>
      </response>
    </answer>
  </action>

  <!-- MAINTAIN ASYNC ACTION (LIKE MAINTAIN SILENT, BUT WITHOUT RESPONSE) -->
  <action id="maintain-async" format="JSON">
    <call service="launchMaintain" />
  </action>

  <!-- DATA SILENT ACTION -->
  <action id="data-silent" format="JSON">
    <call service="launchQuery" />
    <answer type="ok">
      <response>
        <type>end-load</type>
      </response>
    </answer>
    <answer type="warning">
      <response>
        <type>end-load</type>
      </response>
      <response>
        <type>message</type>
        <parameters>
          <parameter name="type" variable="MESSAGE_TYPE" />
          <parameter name="title" variable="MESSAGE_TITLE" />
          <parameter name="message" variable="MESSAGE_DESCRIPTION" />
        </parameters>
      </response>
      <response>
        <type>cancel</type>
      </response>
    </answer>
    <answer type="info">
      <response>
        <type>end-load</type>
      </response>
      <response>
        <type>message</type>
        <parameters>
          <parameter name="type" variable="MESSAGE_TYPE" />
          <parameter name="title" variable="MESSAGE_TITLE" />
          <parameter name="message" variable="MESSAGE_DESCRIPTION" />
        </parameters>
      </response>
    </answer>
    <answer type="error">
      <response>
        <type>end-load</type>
      </response>
      <response>
        <type>message</type>
        <parameters>
          <parameter name="type" value="error" />
          <parameter name="title" variable="MESSAGE_TITLE" />
          <parameter name="message" variable="MESSAGE_DESCRIPTION" />
        </parameters>
      </response>
      <response>
        <type>cancel</type>
      </response>
    </answer>
  </action>

  <!-- DATA SILENT ACTION -->
  <action id="update-model" format="JSON">
    <call service="updateModel" />
    <answer type="ok">
      <response>
        <type>end-load</type>
      </response>
    </answer>
    <answer type="warning">
      <response>
        <type>end-load</type>
      </response>
      <response>
        <type>message</type>
        <parameters>
          <parameter name="type" variable="MESSAGE_TYPE" />
          <parameter name="title" variable="MESSAGE_TITLE" />
          <parameter name="message" variable="MESSAGE_DESCRIPTION" />
        </parameters>
      </response>
    </answer>
    <answer type="info">
      <response>
        <type>end-load</type>
      </response>
      <response>
        <type>message</type>
        <parameters>
          <parameter name="type" variable="MESSAGE_TYPE" />
          <parameter name="title" variable="MESSAGE_TITLE" />
