=== aweframework/awe/awe-framework/awe-generic-screens/src/main/resources/schemas/awe/email.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!--
  ==============================================================================
  Definition
  ==============================================================================
  -->

  <xs:annotation>
    <xs:appinfo>awe Email Schema</xs:appinfo>
    <xs:documentation xml:lang="en">
      This Schema defines the way an awe Email file must be structured
    </xs:documentation>
  </xs:annotation>

  <!--
  ==============================================================================
  Includes
  ==============================================================================
  -->

  <xs:include schemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/variable.xsd"/>

  <!--
  ==============================================================================
  Elements
  ==============================================================================
  -->

  <!-- Emails Element -->
  <xs:element name="emails" type="emailsType"/>

  <!-- Email Element -->
  <xs:element name="email" type="emailType"/>

  <!-- From Element -->
  <xs:element name="from" type="emailItemType"/>

  <!-- To Element -->
  <xs:element name="to" type="emailItemType"/>

  <!-- Cc Element -->
  <xs:element name="cc" type="emailItemType"/>

  <!-- Cco Element -->
  <xs:element name="cco" type="emailItemType"/>

  <!-- Subject Element -->
  <xs:element name="subject" type="emailMessageType"/>

  <!-- Body Element -->
  <xs:element name="body" type="emailMessageType"/>

  <!-- Attachment Element -->
  <xs:element name="attachment" type="emailItemType"/>

  <!-- Variable Element -->
  <xs:element name="variable" type="variableEmailType"/>

  <!--
  ==============================================================================
  Attribute Groups
  ==============================================================================
  -->

  <!-- Email Default Attributes -->
  <xs:attributeGroup name="emailDefaultAttr">
    <xs:attribute name="query" type="xs:string"/>
  </xs:attributeGroup>

  <!-- Email Attributes -->
  <xs:attributeGroup name="emailAttr">
    <xs:attribute name="id" use="required" type="xs:string"/>
    <xs:attribute name="async" use="optional" type="booleanEnum"/>
    <xs:attributeGroup ref="emailDefaultAttr"/>
  </xs:attributeGroup>

  <!-- Email Item Default Attributes -->
  <xs:attributeGroup name="emailMessageDefaultAttr">
    <xs:attribute name="type" type="emailTypeRestriction"/>
    <xs:attributeGroup ref="emailDefaultAttr"/>
  </xs:attributeGroup>

  <!-- Email Item Attributes -->
  <xs:attributeGroup name="emailMessageAttr">
    <xs:attribute name="label" use="required" type="xs:string"/>
    <xs:attribute name="value" type="xs:string"/>
    <xs:attributeGroup ref="emailMessageDefaultAttr"/>
  </xs:attributeGroup>

  <!-- Email Message Attributes -->
  <xs:attributeGroup name="emailItemAttr">
    <xs:attribute name="label" type="xs:string"/>
    <xs:attribute name="value" use="required" type="xs:string"/>
    <xs:attributeGroup ref="emailMessageDefaultAttr"/>
  </xs:attributeGroup>

  <!--
  ==============================================================================
  Group definitions
  ==============================================================================
  -->

  <!-- Emails Group -->
  <xs:group name="emailsGroup">
    <xs:sequence>
      <xs:element ref="email"/>
    </xs:sequence>
  </xs:group>

  <!-- Email Group -->
  <xs:group name="emailGroup">
    <xs:choice>
      <xs:element ref="from"/>
      <xs:element ref="to"/>
      <xs:element ref="cc"/>
      <xs:element ref="cco"/>
      <xs:element ref="subject"/>
      <xs:element ref="body"/>
      <xs:element ref="attachment"/>
      <xs:element ref="variable"/>
    </xs:choice>
  </xs:group>

  <!--
  ==============================================================================
  Type definitions
  ==============================================================================
  -->

  <!-- Emails Type -->
  <xs:complexType name="emailsType">
    <xs:group ref="emailsGroup" minOccurs="0" maxOccurs="unbounded"/>
  </xs:complexType>

  <!-- Email Type -->
  <xs:complexType name="emailType">
    <xs:group ref="emailGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attributeGroup ref="emailAttr"/>
  </xs:complexType>

  <!-- Email Item Type -->
  <xs:complexType name="emailItemType">
    <xs:attributeGroup ref="emailItemAttr"/>
  </xs:complexType>

  <!-- Email Message Type -->
  <xs:complexType name="emailMessageType">
    <xs:attributeGroup ref="emailMessageAttr"/>
  </xs:complexType>

  <!--
  ==============================================================================
  Restriction definitions
  ==============================================================================
  -->

  <!-- Email Type Restriction -->
  <xs:simpleType name="emailTypeRestriction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="html"/>
      <xs:enumeration value="text"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== aweframework/awe/awe-framework/awe-modules/awe-notifier/src/main/resources/application/awe-notifier/global/Email.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : Email.xml
    Created on : 28 de Noviembre de 2011
    Author     : Aitor UGARTE
    Description: Email define file
-->

<emails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/email.xsd">
  <email id="notify-users">
    <from label="FromName" value="FromEmail" />
    <to query="GetEmaLst" label="UsrNam" value="UsrEml" />
    <subject label="EMAIL_SUBJECT_NOTIFY" value="asd"/>
    <body label="EMAIL_MESSAGE_HTML_HEADER" type="html" value=""/>
    <body label="EMAIL_MESSAGE_HTML_NOTIFY" type="html" value=""/>
    <body label="EMAIL_MESSAGE_HTML_BOTTOM" type="html" value=""/>
    <body label="EMAIL_MESSAGE_TEXT_NOTIFY" type="text" value=""/>
    <variable id="FromName" type="STRING" property="awe.notifier.from-name"/>
    <variable id="FromEmail" type="STRING" property="awe.notifier.from-email"/>
    <variable id="title" type="STRING" name="title"/>
    <variable id="subscription" type="STRING" name="subscription"/>
    <variable id="description" type="STRING" name="description"/>
  </email>
</emails>

=== aweframework/awe/awe-framework/awe-modules/awe-scheduler/src/main/resources/application/awe-scheduler/global/Email.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : Email.xml
    Created on : 28 de Noviembre de 2011
    Author     : Aitor UGARTE
    Description: Email define file
-->

<emails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/email.xsd">
  <email id="SchTskEmaRep">
    <from label="FromValue" value="FromValue" />
    <to label="ToValue" value="ToValue" />
    <subject label="RepTit" value="RepTit" />
    <body label="RepMsg" type="html" value="RepMsgHtml"/>
    <body label="RepMsg" type="text" value="RepMsgText"/>
    <variable type="STRING" id="FromValue" property="awe.scheduler.report-email-from-value" />
    <variable type="STRING" id="ToValue" name="ToValue"/>
    <variable type="STRING" id="RepTit" name="RepTit"/>
    <variable type="STRING" id="RepMsgHtml" name="RepMsgHtml"/>
    <variable type="STRING" id="RepMsgText" name="RepMsgText"/>
  </email>
</emails>

=== aweframework/awe/awe-tests/awe-boot/src/main/resources/application/awe-boot/global/Email.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : Email.xml
    Created on : 28 de Noviembre de 2011
    Author     : Aitor UGARTE
    Description: Email define file
-->

<emails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/email.xsd">
  <email id="SndRep">
    <from query="SesUsr" label="SesNam" value="SesEma" />
    <to query="GetEmaLst" label="UsrNam" value="UsrEml" />
    <subject label="EMAIL_SUBJECT_REPORT" />
    <body label="EMAIL_MESSAGE_HTML_HEADER" type="html" />
    <body label="EMAIL_MESSAGE_HTML_REPORT" type="html" />
    <body label="EMAIL_MESSAGE_HTML_BOTTOM" type="html" />
    <body label="EMAIL_MESSAGE_TEXT_REPORT" type="text" />
    <attachment value="PdfNam" label="EMAIL_FILE_PDF" />
    <attachment value="DocNam" label="EMAIL_FILE_DOC" />
    <attachment value="XlsNam" label="EMAIL_FILE_XLS" />
    <attachment value="CsvNam" label="EMAIL_FILE_CSV" />
    <attachment value="TxtNam" label="EMAIL_FILE_TXT" />
    <variable id="ScrTit" type="STRING" name="ScrTit"/>
    <variable id="ScrTitFil" type="STRING" name="ScrTitFil"/>
    <variable id="PdfNam" type="STRING" name="PdfNam" optional="true"/>
    <variable id="DocNam" type="STRING" name="DocNam" optional="true"/>
    <variable id="XlsNam" type="STRING" name="XlsNam" optional="true"/>
    <variable id="CsvNam" type="STRING" name="CsvNam" optional="true"/>
    <variable id="TxtNam" type="STRING" name="TxtNam" optional="true"/>
  </email>

  <email id="EmlActUsr">
    <from query="SesUsr" label="SesNam" value="SesEma" />
    <to query="GetActUsrEmaLst" label="UsrNam" value="UsrEml" />
    <subject label="EMAIL_SUBJECT_GENERAL" />
    <body label="EMAIL_MESSAGE_HTML_HEADER" type="html" />
    <body label="EMAIL_MESSAGE_HTML_GENERAL" type="html" />
    <body label="EMAIL_MESSAGE_HTML_BOTTOM" type="html" />
    <body label="EMAIL_MESSAGE_TEXT_GENERAL" type="text" />
  </email>

  <email id="TestEmail"/>

</emails>
