=== aweframework/awe/awe-framework/awe-generic-screens/src/main/resources/schemas/awe/enumerated.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!--
  ==============================================================================
  Definition
  ==============================================================================
  -->

  <xs:annotation>
    <xs:appinfo>awe Enumerated Schema</xs:appinfo>
    <xs:documentation xml:lang="en">
      This Schema defines the way an awe Enumerated file must be structured
    </xs:documentation>
  </xs:annotation>

  <!--
  ==============================================================================
  Includes
  ==============================================================================
  -->

  <xs:include schemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/general.xsd"/>

  <!--
  ==============================================================================
  Elements
  ==============================================================================
  -->

  <!-- Enumerated Element -->
  <xs:element name="enumerated" type="enumeratedType">
    <xs:unique name="GroupNameUnique">
      <xs:selector xpath=".//group" />
      <xs:field xpath="@id" />
    </xs:unique>
  </xs:element>

  <!-- Group Element -->
  <xs:element name="group" type="groupType"/>

  <!-- Option Element -->
  <xs:element name="option" type="optionType"/>

  <!--
  ==============================================================================
  Type definitions
  ==============================================================================
  -->

  <!-- Enumerated Type -->
  <xs:complexType name="enumeratedType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="group"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Group Type -->
  <xs:complexType name="groupType">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" ref="option"/>
    </xs:sequence>
    <xs:attribute name="id" use="required" type="xs:string"/>
  </xs:complexType>

  <!-- Option Type -->
  <xs:complexType name="optionType">
    <xs:attribute name="label" use="required" type="xs:string"/>
    <xs:attribute name="value" use="required" type="xs:string"/>
  </xs:complexType>

</xs:schema>

=== aweframework/awe/awe-framework/awe-modules/awe-notifier/src/main/resources/application/awe-notifier/global/Enumerated.xml
<?xml version="1.0" encoding="UTF-8"?>


<enumerated xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/enumerated.xsd">

  <group id="notification-label">
    <option label="ENUM_NOTIFICATION_NORMAL" value="NORMAL"/>
    <option label="ENUM_NOTIFICATION_OK" value="OK"/>
    <option label="ENUM_NOTIFICATION_INFO" value="INFO"/>
    <option label="ENUM_NOTIFICATION_WARNING" value="WARNING"/>
    <option label="ENUM_NOTIFICATION_ERROR" value="ERROR"/>
  </group>

  <group id="notification-type">
    <option label="default" value="NORMAL"/>
    <option label="success" value="OK"/>
    <option label="info" value="INFO"/>
    <option label="warning" value="WARNING"/>
    <option label="danger" value="ERROR"/>
  </group>

  <group id="notification-style">
    <option label="bg-default" value="NORMAL"/>
    <option label="bg-success" value="OK"/>
    <option label="bg-info" value="INFO"/>
    <option label="bg-warning" value="WARNING"/>
    <option label="bg-danger" value="ERROR"/>
  </group>

  <group id="notification-read-icon">
    <option label="fa-eye" value="0"/>
    <option label="fa-eye-slash" value="1"/>
  </group>

  <group id="active-icon-button">
    <option label="times" value="0"/>
    <option label="check" value="1"/>
  </group>

  <group id="notification-read-style">
    <option label="text-success" value="0"/>
    <option label="text-danger" value="1"/>
  </group>

  <group id="notification-read-label">
    <option label="ENUM_NOTIFICATION_READ" value="0"/>
    <option label="ENUM_NOTIFICATION_UNREAD" value="1"/>
  </group>

  <group id="unread-style">
    <option label="faded" value="0"/>
    <option label="" value="1"/>
  </group>

  <group id="user-settings">
    <option label="PROFILE" value="profile"/>
    <option label="SECURITY" value="security"/>
    <option label="NOTIFICATIONS" value="notifications"/>
  </group>

</enumerated>

=== aweframework/awe/awe-tests/awe-boot/src/main/resources/application/awe-boot/global/Enumerated.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : Enumerated.xml
    Created on : 11 de marzo de 2010, 11:03
    Author     : Pablo GARCIA
    Description:
        Purpose of the document follows.
-->

<enumerated xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/enumerated.xsd">

  <!-- LANGUAGES -->
  <group id="Lan">
    <option label="ENUM_LAN_ES-ES" value="es-ES" />
    <option label="ENUM_LAN_EN-GB" value="en-GB" />
    <option label="ENUM_LAN_FR-FR" value="fr-FR" />
  </group>

  <!-- MATRIX TEST TYPE -->
  <group id="EnuAweSelMat">
    <option label="ENUM_MATRIX_STATIC" value="StaMat" />
    <option label="ENUM_MATRIX_MULTISELECT" value="MusMat" />
    <option label="ENUM_MATRIX_EDITABLE" value="EdiMat" />
    <option label="ENUM_MATRIX_EDITABLE_MULTISELECT" value="EdiMusMat" />
    <option label="ENUM_MATRIX_MULTIOPTION" value="MuoMat" />
    <option label="ENUM_MATRIX_TREEGRID" value="TreMat" />
    <option label="ENUM_MATRIX_TREEGRID_LOADNODE" value="TreLoaMat" />
    <option label="ENUM_MATRIX_TREEGRID_EDITABLE" value="TreEdiMat" />
    <option label="ENUM_MATRIX_TREEGRID_EDITABLE_LOADNODE" value="TreLoaEdiMat" />
    <option label="ENUM_MATRIX_TOTALIZE" value="TotMat" />
    <option label="ENUM_MATRIX_TOTALIZE_SERVICE" value="TotSrvMat" />
    <option label="ENUM_MATRIX_GRID_DEPENDENCIES" value="DepMat" />
  </group>

  <!-- WIZARD TEST STEPS -->
  <group id="WizTst">
    <option label="ENUM_STEP_1" value="WizardStep1" />
    <option label="ENUM_STEP_2" value="WizardStep2" />
    <option label="ENUM_STEP_3" value="WizardStep3" />
    <option label="ENUM_STEP_4" value="WizardStep4" />
  </group>
</enumerated>
