=== aweframework/awe/awe-framework/awe-generic-screens/src/main/resources/schemas/awe/menu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!--
  ==============================================================================
  Definition
  ==============================================================================
  -->

  <xs:annotation>
    <xs:appinfo>awe Menu Schema</xs:appinfo>
    <xs:documentation xml:lang="en">
      This Schema defines the way an awe Menu file must be structured
    </xs:documentation>
  </xs:annotation>

  <!--
  ==============================================================================
  Includes
  ==============================================================================
  -->

  <xs:include schemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/general.xsd"/>

  <!--
  ==============================================================================
  Elements
  ==============================================================================
  -->

  <!-- Menu Element -->
  <xs:element name="menu" type="menuType">
    <xs:unique name="OptionNameUnique">
      <xs:selector xpath=".//option" />
      <xs:field xpath="@name" />
    </xs:unique>
  </xs:element>

  <!-- Option Element -->
  <xs:element name="option" type="optionType"/>

  <!--
  ==============================================================================
  Attribute Groups
  ==============================================================================
  -->

  <!-- Email Default Attributes -->
  <xs:attributeGroup name="menuAttr">
    <xs:attribute name="context" type="xs:string"/>
    <xs:attribute name="default-action" type="serverActionEnum"/>
    <xs:attribute name="screen" use="required" type="xs:string"/>
  </xs:attributeGroup>

  <!-- Option Default Attributes -->
  <xs:attributeGroup name="optionAttr">
    <xs:attribute name="module" type="xs:string"/>
    <xs:attribute name="invisible" type="booleanEnum"/>
    <xs:attribute name="label" type="xs:string"/>
    <xs:attribute name="name" use="required" type="xs:string"/>
    <xs:attribute name="screen" type="xs:string"/>
    <xs:attribute name="separator" type="booleanEnum"/>
    <xs:attribute name="icon" type="xs:string"/>
    <xs:attribute name="menu-screen" type="booleanEnum"/>
    <xs:attribute name="server-action" type="serverActionEnum"/>
    <xs:attribute name="target-action" type="xs:string"/>
  </xs:attributeGroup>

  <!--
  ==============================================================================
  Type definitions
  ==============================================================================
  -->

  <!-- Menu Type -->
  <xs:complexType name="menuType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="option"/>
    </xs:sequence>
    <xs:attributeGroup ref="menuAttr"/>
  </xs:complexType>

  <!-- Option Type -->
  <xs:complexType name="optionType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="option"/>
    </xs:sequence>
    <xs:attributeGroup ref="optionAttr"/>
  </xs:complexType>

</xs:schema>

=== aweframework/awe/awe-framework/awe-boot-react-archetype/src/main/resources/archetype-resources/src/main/resources/application/__artifactId__/menu/private.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : private.xml
    Author     : Pablo GARCIA
    Description: Private profile options
-->
<menu screen="home-sidebar" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/menu.xsd"
      context="screen/private/home" default-action="screen">
  <option name="information" screen="info" invisible="true" />
  <option name="tools" label="MENU_TOOLS" icon="wrench">
    <option name="sites" label="MENU_TOOLS_SITES" screen="Sit" icon="sitemap">
      <option name="new-site" screen="SitNew" invisible="true" />
      <option name="update-site" screen="SitUpd" invisible="true" />
      <option name="view-site" screen="SitViw" invisible="true" />
    </option>
    <option name="modules" label="MENU_TOOLS_MODULES" screen="Mod" icon="puzzle-piece">
      <option name="new-module" screen="ModNew" invisible="true" />
      <option name="update-module" screen="ModUpd" invisible="true" />
      <option name="view-module" screen="ModViw" invisible="true" />
    </option>
    <option name="users" label="MENU_TOOLS_USERS" screen="Usr" icon="user">
      <option name="new-user" screen="UsrNew" invisible="true" />
      <option name="update-user" screen="UsrUpd" invisible="true" />
      <option name="view-user" screen="UsrViw" invisible="true" />
    </option>
    <option name="profiles" label="MENU_TOOLS_PROFILES" screen="Prf" icon="group">
      <option name="new-profile" screen="PrfNew" invisible="true" />
      <option name="update-profile" screen="PrfUpd" invisible="true" />
      <option name="view-profile" screen="PrfViw" invisible="true" />
    </option>
    <option name="databases" label="MENU_TOOLS_DATABASE" screen="Dbs" icon="database">
      <option name="new-database" screen="DbsNew" invisible="true" />
      <option name="update-database" screen="DbsUpd" invisible="true" />
      <option name="view-database" screen="DbsViw" invisible="true" />
    </option>
    <option name="themes" label="MENU_TOOLS_THEMES" screen="Thm" icon="picture-o">
      <option name="new-theme" screen="ThmNew" invisible="true" />
      <option name="update-theme" screen="ThmUpd" invisible="true" />
      <option name="view-theme" screen="ThmViw" invisible="true" />
      <option name="customize-theme" screen="customize-themes" invisible="true"/>
    </option>
    <option name="email-servers" label="MENU_TOOLS_AWE_EML_SRV" screen="EmlSrv" icon="envelope">
      <option name="new-email-server" screen="EmlSrvNew" invisible="true" />
      <option name="update-email-server" screen="EmlSrvUpd" invisible="true" />
    </option>
    <option name="queues" label="MENU_TOOLS_AWE_QUE" screen="Que" icon="exchange">
      <option name="new-queue" screen="QueNew" invisible="true" />
      <option name="update-queue" screen="QueUpd" invisible="true" />
    </option>
    <option name="sequences" label="MENU_TOOLS_AWEKEY" screen="AweKey" icon="key" />
    <option name="application-parameters" label="MENU_TOOLS_AWE_APPPAR" screen="AweAppPar" icon="cogs" />
    <option name="broadcast-messages" label="MENU_BROADCAST" screen="MsgUsr" icon="rss" />
    <option name="log" label="MENU_LOG" screen="Log" icon="file-text">
      <option name="view-log" screen="LogViw" invisible="true" />
    </option>
  </option>
  <option name="settings" label="MENU_SETTINGS" icon="cog">
    <option name="security" label="MENU_TOOLS_SECURITY" icon="unlock-alt">
      <option name="screen-access" label="MENU_TOOLS_SCREENS_ACCESS" screen="ScrAccRes" icon="eye-slash" />
      <option name="encrypt-tools" label="MENU_TOOLS_SCREEN_ENCRYPT" screen="ScrEncTxt" icon="lock" />
    </option>
    <option name="screen-configuration" label="MENU_TOOLS_SCR_CNF" screen="ScrCnf" icon="laptop" />
  </option>
  <option name="help-separator" separator="true" />
  <option name="help" label="MENU_HELP" icon="question-circle">
    <option name="user-help" label="MENU_USER_HELP" screen="application-manual" icon="book" />
    <option name="application-help" label="MENU_HELP_APPLICATION" screen="application-help" icon="question" />
    <option name="application-info" label="MENU_APP_INF" screen="ViwAppInf" icon="info" />
  </option>
</menu>

=== aweframework/awe/awe-tests/awe-scheduler-boot/src/main/resources/application/awe-scheduler-boot/menu/private.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : private.xml
    Created on : 10 de febrero de 2010, 13:08
    Author     : Pablo GARCIA
    Description: Private profile options
-->
<menu screen="home_horizontal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/menu.xsd" context="screen/private/home" default-action="screen">
  <option name="information" screen="info" invisible="true"/>
  <option name="tools" label="MENU_TOOLS" icon="wrench">
    <option name="sites" label="MENU_TOOLS_SITES" screen="Sit" icon="sitemap">
      <option name="new-site" screen="SitNew" invisible="true"/>
      <option name="update-site" screen="SitUpd" invisible="true"/>
      <option name="view-site" screen="SitViw" invisible="true"/>
    </option>
    <option name="modules" label="MENU_TOOLS_MODULES" screen="Mod" icon="puzzle-piece">
      <option name="new-module" screen="ModNew" invisible="true"/>
      <option name="update-module" screen="ModUpd" invisible="true"/>
      <option name="view-module" screen="ModViw" invisible="true"/>
    </option>
    <option name="users" label="MENU_TOOLS_USERS" screen="Usr" icon="user">
      <option name="new-user" screen="UsrNew" invisible="true"/>
      <option name="update-user" screen="UsrUpd" invisible="true"/>
      <option name="view-user" screen="UsrViw" invisible="true"/>
    </option>
    <option name="profiles" label="MENU_TOOLS_PROFILES" screen="Prf" icon="group">
      <option name="new-profile" screen="PrfNew" invisible="true"/>
      <option name="update-profile" screen="PrfUpd" invisible="true"/>
      <option name="view-profile" screen="PrfViw" invisible="true"/>
    </option>
    <option name="databases" label="MENU_TOOLS_DATABASE" screen="Dbs" icon="database">
      <option name="new-database" screen="DbsNew" invisible="true"/>
      <option name="update-database" screen="DbsUpd" invisible="true"/>
      <option name="view-database" screen="DbsViw" invisible="true"/>
    </option>
    <option name="themes" label="MENU_TOOLS_THEMES" screen="Thm" icon="picture-o">
      <option name="new-theme" screen="ThmNew" invisible="true"/>
      <option name="update-theme" screen="ThmUpd" invisible="true"/>
      <option name="view-theme" screen="ThmViw" invisible="true"/>
      <option name="customize-theme" screen="customize-themes" invisible="true"/>
    </option>
    <option name="email-servers" label="MENU_TOOLS_AWE_EML_SRV" screen="EmlSrv" icon="envelope">
      <option name="new-email-server" screen="EmlSrvNew" invisible="true"/>
      <option name="update-email-server" screen="EmlSrvUpd" invisible="true"/>
    </option>
    <option name="queues" label="MENU_TOOLS_AWE_QUE" screen="Que" icon="exchange">
      <option name="new-queue" screen="QueNew" invisible="true"/>
      <option name="update-queue" screen="QueUpd" invisible="true"/>
    </option>
    <option name="sequences" label="MENU_TOOLS_AWEKEY" screen="AweKey" icon="key"/>
    <option name="application-parameters" label="MENU_TOOLS_AWE_APPPAR" screen="AweAppPar" icon="cogs"/>
    <option name="broadcast-messages" label="MENU_BROADCAST" screen="MsgUsr" icon="rss"/>
    <option name="log" label="MENU_LOG" screen="Log" icon="file-text">
      <option name="view-log" screen="LogViw" invisible="true"/>
    </option>
    <option name="sqlExtractor" label="MENU_SQL_EXTRACTOR" screen="sqlExtractor" icon="database"/>
  </option>
  <option name="settings" label="MENU_SETTINGS" icon="cog">
    <option name="security" label="MENU_TOOLS_SECURITY" icon="unlock-alt">
      <option name="screen-access" label="MENU_TOOLS_SCREENS_ACCESS" screen="ScrAccRes" icon="eye-slash"/>
      <option name="encrypt-tools" label="MENU_TOOLS_SCREEN_ENCRYPT" screen="ScrEncTxt" icon="lock"/>
    </option>
    <option name="screen-configuration" label="MENU_TOOLS_SCR_CNF" screen="ScrCnf" icon="laptop"/>
  </option>
  <option name="scheduler-separator" separator="true"/>
  <option name="scheduler" label="MENU_SCHEDULER" icon="clock-o">
    <option name="scheduler-management" label="MENU_SCHEDULER_MANAGEMENT" screen="scheduler-management" icon="cogs"/>
    <option name="scheduler-tasks" label="MENU_SCHEDULER_TASKS" screen="scheduler-tasks" icon="tasks">
      <option name="new-scheduler-task" screen="new-scheduler-task" invisible="true" />
      <option name="update-scheduler-task" screen="update-scheduler-task" invisible="true" />
    </option>
    <option name="scheduler-servers" label="MENU_SCHEDULER_SERVERS" screen="scheduler-server" icon="server">
      <option name="new-scheduler-server" screen="new-scheduler-server" invisible="true" />
      <option name="update-scheduler-server" screen="update-scheduler-server" invisible="true" />
    </option>
    <option name="scheduler-calendars" label="MENU_SCHEDULER_CALENDARS" screen="scheduler-calendars" icon="calendar">
      <option name="new-scheduler-calendar" screen="new-scheduler-calendar" invisible="true" />
      <option name="update-scheduler-calendar" screen="update-scheduler-calendar" invisible="true" />
    </option>
  </option>
  <option name="notifier-separator" separator="true"/>
  <option name="user-settings" screen="user-settings" invisible="true"/>
  <option name="notifier" label="MENU_NOTIFIER" icon="flash">
    <option name="subscriptions" screen="subscriptions" label="MENU_NOTIFIER_SUBSCRIPTIONS" icon="ticket">
      <option name="new-subscription" screen="new-subscription" invisible="true" />
      <option name="update-subscription" screen="update-subscription" invisible="true" />
    </option>
    <option name="notifications" screen="notifications" label="MENU_NOTIFIER_NOTIFICATIONS" icon="bell" />
  </option>
  <option name="developer-separator" separator="true"/>
  <option name="developer" label="MENU_DEVELOPER" icon="paint-brush">
    <option name="path-manager" label="MENU_PATH" screen="path-manager" icon="terminal"/>
    <option name="local-manager" label="MENU_LANGUAGES" screen="local-manager" icon="language"/>
  </option>
  <option name="help-separator" separator="true"/>
  <option name="help" label="MENU_HELP" icon="question-circle">
    <option name="user-help" label="MENU_USER_HELP" screen="application-manual" icon="book"/>
    <option name="application-help" label="MENU_HELP_APPLICATION" screen="application-help" icon="question"/>
    <option name="application-info" label="MENU_APP_INF" screen="ViwAppInf" icon="info"/>
  </option>
</menu>

=== aweframework/awe/awe-tests/awe-boot/src/main/resources/application/awe-boot/menu/public.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : public.xml
    Created on : 10 de febrero de 2010, 13:16
    Author     : Pablo GARCIA
    Description: Public profile options
-->
<menu screen="signin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/menu.xsd" context="screen" default-action="screen">
  <option name="signin" screen="signin" invisible="true" />
  <option name="change-password" screen="change-password" invisible="true" />
  <option name="check-2fa" screen="check-2fa" invisible="true" />
  <option name="activate-2fa" screen="activate-2fa" invisible="true" />
  <option name="information" screen="info" invisible="true" />
  <option name="test-initial-load" screen="TestInitialLoad" invisible="true" />
  <option name="test-initial-values" screen="TestInitialValues" invisible="true" />
  <option name="test-initial-values-load" screen="TestInitialValuesLoad" invisible="true" />
  <option name="error-4xx" screen="error-4xx" invisible="true" />
  <option name="error-5xx" screen="error-5xx" invisible="true" />
</menu>
