=== aweframework/awe/awe-framework/awe-generic-screens/src/main/resources/schemas/awe/services.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!--
  ==============================================================================
  Definition
  ==============================================================================
  -->

  <xs:annotation>
    <xs:appinfo>awe Services Schema</xs:appinfo>
    <xs:documentation xml:lang="en">
      This Schema defines the way an awe Services file must be structured
    </xs:documentation>
  </xs:annotation>

  <!--
  ==============================================================================
  Includes
  ==============================================================================
  -->

  <xs:include schemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/general.xsd"/>

  <!--
  ==============================================================================
  Elements
  ==============================================================================
  -->

  <!-- Services Element -->
  <xs:element name="services" type="servicesType">
    <xs:unique name="ServiceKey">
      <xs:selector xpath=".//service" />
      <xs:field xpath="@id" />
    </xs:unique>
  </xs:element>

  <!-- Service Element -->
  <xs:element name="service" type="serviceType"/>

  <!-- Java Element -->
  <xs:element name="java" type="javaType"/>

  <!-- Microservice Element -->
  <xs:element name="microservice" type="microserviceType"/>

  <!-- Rest Element -->
  <xs:element name="rest" type="restType"/>

  <!-- Service Parameter Element -->
  <xs:element name="service-parameter" type="serviceParameterType"/>

  <!--
  ==============================================================================
  Type definitions
  ==============================================================================
  -->

  <!-- Services Type -->
  <xs:complexType name="servicesType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="service"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Service Type -->
  <xs:complexType name="serviceType">
    <xs:choice>
      <xs:element ref="java"/>
      <xs:element ref="microservice"/>
      <xs:element ref="rest"/>
    </xs:choice>
    <xs:attribute name="id" use="required" type="xs:string"/>
    <xs:attribute name="launch-phase" type="launchPhaseEnum"/>
  </xs:complexType>

  <!-- Java Type -->
  <xs:complexType name="javaType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="service-parameter"/>
    </xs:sequence>
    <xs:attribute name="classname" use="required"/>
    <xs:attribute name="method" use="required" type="xs:string"/>
    <xs:attribute name="qualifier" type="xs:string"/>
  </xs:complexType>

  <!-- Microservice Type -->
  <xs:complexType name="microserviceType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="service-parameter"/>
    </xs:sequence>
    <xs:attribute name="name" use="required" type="xs:string"/>
    <xs:attribute name="endpoint" use="required" type="xs:string"/>
    <xs:attribute name="method" use="required" type="methodEnum"/>
    <xs:attribute name="wrapper" type="xs:string"/>
    <xs:attribute name="content-type" type="contentTypeEnum"/>
  </xs:complexType>

  <!-- Rest Type -->
  <xs:complexType name="restType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="service-parameter"/>
    </xs:sequence>
    <xs:attribute name="server" type="xs:string"/>
    <xs:attribute name="endpoint" use="required" type="xs:string"/>
    <xs:attribute name="method" use="required" type="methodEnum"/>
    <xs:attribute name="wrapper" type="xs:string"/>
    <xs:attribute name="content-type" type="contentTypeEnum"/>
  </xs:complexType>

  <!-- Jms Type -->
  <xs:complexType name="jmsType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="service-parameter"/>
    </xs:sequence>
    <xs:attribute name="name" use="required" type="xs:string"/>
    <xs:attribute name="type" use="required" type="serviceTypeRestriction"/>
    <xs:attribute name="timeout" type="xs:string"/>
    <xs:attribute name="cacheable" type="booleanEnum"/>
  </xs:complexType>

  <!-- Service Parameter Type -->
  <xs:complexType name="serviceParameterType">
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="type" use="required" type="serviceVariableRestriction"/>
    <xs:attribute name="value" type="xs:string"/>
    <xs:attribute name="list" type="booleanEnum"/>
    <xs:attribute name="bean-class" type="xs:string"/>
  </xs:complexType>

  <!-- Service Variable Restriction -->
  <xs:simpleType name="launchPhaseEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="APPLICATION_START"/>
      <xs:enumeration value="APPLICATION_END"/>
      <xs:enumeration value="CLIENT_START"/>
      <xs:enumeration value="CLIENT_END"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Service Method Restriction -->
  <xs:simpleType name="methodEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="GET"/>
      <xs:enumeration value="POST"/>
      <xs:enumeration value="PUT"/>
      <xs:enumeration value="DELETE"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Content type Restriction -->
  <xs:simpleType name="contentTypeEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="JSON"/>
      <xs:enumeration value="URLENCODED"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== aweframework/awe/awe-framework/awe-modules/awe-scheduler/src/main/resources/application/awe-scheduler/global/Services.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--$Id$ -->
<services xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/services.xsd">

  <!-- SCHEDULER SERVICES -->

  <!-- scheduler tasks -->
  <service id="getSchedulerTaskList">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="getTaskList">
      <service-parameter type="OBJECT" bean-class="com.almis.awe.scheduler.bean.task.TaskListCriteria" name="taskListCriteria"/>
    </java>
  </service>

  <service id="nextExecutions">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="computeNextFireTimes">
      <service-parameter name="fireTimes" type="INTEGER"/>
    </java>
  </service>

  <service id="getTaskExecutionList">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="getTaskExecutionList">
      <service-parameter type="INTEGER" name="taskId"/>
    </java>
  </service>

  <service id="pauseTask">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="pauseTask">
      <service-parameter name="IdeTsk" type="INTEGER"/>
    </java>
  </service>
  <service id="resumeTask">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="resumeTask">
      <service-parameter name="IdeTsk" type="INTEGER"/>
    </java>
  </service>
  <service id="executeTaskNow">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="executeTaskNow">
      <service-parameter name="taskIde" type="INTEGER"/>
      <service-parameter name="user" type="STRING"/>
    </java>
  </service>
  <!-- Manual launch applying operator-supplied values to the variable (source = "1") parameters.
       The bean-class + list="true" parameter is bound by the JavaConnector as List.class, resolving
       RemoteSchedulerService.executeTaskNow(Integer, String, List<TaskVariable>). The TaskVariable
       field names (name/value) must match the modal grid column names. -->
  <service id="executeTaskNowVariables">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="executeTaskNow">
      <service-parameter name="taskIde" type="INTEGER"/>
      <service-parameter name="user" type="STRING"/>
      <service-parameter name="variables" type="OBJECT" bean-class="com.almis.awe.scheduler.bean.task.TaskVariable" list="true"/>
    </java>
  </service>

  <service id="insertSchedulerTask">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="insertSchedulerTask">
      <service-parameter name="IdeTsk" type="INTEGER"/>
    </java>
  </service>
  <service id="updateSchedulerTask">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="updateSchedulerTask">
      <service-parameter name="IdeTsk" type="INTEGER"/>
    </java>
  </service>
  <service id="deleteSchedulerTask">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="deleteSchedulerTask">
      <service-parameter name="IdeTsk" type="INTEGER" list="true"/>
    </java>
  </service>

  <service id="purgeExecutionLogs">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="purgeExecutionLogs">
      <service-parameter name="taskId" type="INTEGER"/>
      <service-parameter name="executions" type="INTEGER" />
    </java>
  </service>

  <service id="currentlyExecutingJobs">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="currentlyExecutingJobs"/>
  </service>

  <service id="getConfiguredJobs">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="getConfiguredJobs"/>
  </service>

  <!-- Scheduler calendars -->
  <service id="insertSchedulerCalendar">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="insertSchedulerCalendar">
      <service-parameter name="calendarIde" type="INTEGER"/>
    </java>
  </service>

  <service id="updateSchedulerCalendar">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="updateSchedulerCalendar">
      <service-parameter name="calendarIde" type="INTEGER"/>
    </java>
  </service>

  <service id="deleteSchedulerCalendar">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="deleteSchedulerCalendar">
      <service-parameter name="calendarIde" type="INTEGER" list="true"/>
    </java>
  </service>

  <service id="checkTriggerContainsCalendar">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="checkCalendarExist">
      <service-parameter name="calendarIde" type="INTEGER" list="true"/>
    </java>
  </service>

  <service id="activateSchedulerCalendar">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="activateCalendar">
      <service-parameter name="calendarIde" type="INTEGER" list="true"/>
    </java>
  </service>

  <service id="deactivateSchedulerCalendar">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="deactivateCalendar">
      <service-parameter name="calendarIde" type="INTEGER" list="true"/>
    </java>
  </service>

  <service id="startScheduler">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="start"/>
  </service>

  <service id="stopScheduler">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="stop"/>
  </service>

  <service id="restartScheduler">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="restart"/>
  </service>

  <service id="clearAndStop">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="clearAndStop"/>
  </service>

  <service id="getSchedulerMetadata">
    <java classname="com.almis.awe.scheduler.service.RemoteSchedulerService" method="getSchedulerMetadata"/>
  </service>

  <!-- Services without QUARTZ usage -->
  <service id="startSchedulerQuartz" launch-phase="APPLICATION_START">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="startOnInit"/>
  </service>

  <service id="getExecutionsToPurge">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="getExecutionsToPurge">
      <service-parameter type="INTEGER" name="taskId"/>
      <service-parameter type="INTEGER" name="executions"/>
    </java>
  </service>

  <service id="updateExecutionTime">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="updateExecutionTime">
      <service-parameter name="taskId" type="INTEGER"/>
      <service-parameter name="taskExecution" type="INTEGER"/>
    </java>
  </service>

  <service id="loadMaintainVariables">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="loadMaintainVariables">
      <service-parameter name="maintainStr" type="STRING"/>
    </java>
  </service>

  <!-- Year select/suggest service, returns the next 100 years -->
  <service id="yearSelectService">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="yearSelectService"/>
  </service>

  <service id="loadExecutionScreen">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="loadExecutionScreen">
      <service-parameter name="executionLogPath" type="STRING"/>
      <service-parameter name="address" type="JSON" />
    </java>
  </service>

  <service id="reloadExecutionScreen">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="reloadExecutionScreen">
      <service-parameter name="taskId" type="INTEGER"/>
      <service-parameter name="executionId" type="INTEGER" />
    </java>
  </service>

  <service id="purgeExecutionsAtStart" launch-phase="APPLICATION_START">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="purgeExecutionsAtStart"/>
  </service>

  <service id="launchRemoteSchedulerTask">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="launchRemoteSchedulerTask">
      <service-parameter name="maintainId" type="STRING"/>
      <service-parameter name="parameters" type="OBJECT"/>
      <service-parameter name="callback" type="STRING"/>
    </java>
  </service>

  <service id="reportSchedulerTaskFinished">
    <java classname="com.almis.awe.scheduler.service.report.SchedulerReportService" method="execute">
      <service-parameter name="task" type="JSON" bean-class="com.almis.awe.scheduler.bean.task.Task"/>
      <service-parameter name="taskExecution" type="JSON" bean-class="com.almis.awe.scheduler.bean.task.TaskExecution"/>
    </java>
  </service>

</services>
